server:
  port:  9090
message:  Configuracion del Customer en el servidor levantado;

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/crudcustomer
    username:  postgres
    password:  123456789
    driver-class-name:  org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql:  true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
